name: export typography

on: workflow_dispatch

jobs:
    export:
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'core-ds/ui-primitives' }}
        steps:
            - uses: actions/checkout@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: npm

            - name: install dependencies
              shell: bash
              run: |
                  npm ci

            - name: build scripts
              shell: bash
              run: |
                  npm run build

            - uses: actions/github-script@v8
              env:
                  FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
                  WEB_TYPOGRAPHY_FILE_KEYS: ${{ secrets.WEB_TYPOGRAPHY_FILE_KEYS }}
                  ANDROID_TYPOGRAPHY_FILE_KEYS: ${{ secrets.ANDROID_TYPOGRAPHY_FILE_KEYS }}
                  IOS_TYPOGRAPHY_FILE_KEYS: ${{ secrets.IOS_TYPOGRAPHY_FILE_KEYS }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const { default: main } = await import('${{ github.workspace }}/dist/bin-export-typography.mjs');

                      await main({ github, context, core, glob, io, exec });
